#!/bin/bash -eu

die() { echo "$@" >&2; exit 1; }

PATH+=:
usage="$0 <npicks>"

npicks=${1:?"usage: $usage"}

(( $npicks > 0 )) || die "usage: $usage"
# needs to be better than this

for i in $(eval echo {1..$npicks}); do
  pick
  echo
done
