#!/bin/bash -eux
# Generate a Romanian-lottery pick
#   three sets of half-a-dozen numbers between 1 & 49

for i in {1..3}; do
  echo $(
    for i in {1..3}; do
      echo $RANDOM $i
    done |
    sort -n |
    awk '{print $2}'
  )
done
